[Major]: refactor: use`RouterService` instead of Ember `Router`  (#270)
* chore(deps): upgrade `ember-cli-babel`

This fixes the following error:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: @ember/test-helpers]) in @ember/test-helpers/dom/-is-focusable.js

Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /Users/jan/open-source/ember-router-scroll/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /Users/jan/open-source/ember-router-scroll/node_modules/@babel/preset-env/lib/index.js
- /Users/jan/open-source/ember-router-scroll/node_modules/@babel/core/lib/config/files/plugins.js
- /Users/jan/open-source/ember-router-scroll/node_modules/@babel/core/lib/config/files/index.js
- /Users/jan/open-source/ember-router-scroll/node_modules/@babel/core/lib/index.js
- /Users/jan/open-source/ember-router-scroll/node_modules/broccoli-babel-transpiler/lib/worker.js
```

* refactor: first shot at using `RouterService`

* refactor to master

* fix lockfile

* some improvements to tests.  more to go

* fix some tests

* Fix tests

* fix bug in recursive call

* Update docs

* rm deprecation outdated

* Do not need locations/router-scroll

https://github.com/DockYard/ember-router-scroll/issues/193

* CHANGELOG 4.0.0

* Update addon/services/router-scroll.js

Co-authored-by: John Leja <john.leja@dockyard.com>

* fix comment

* Address some feedback

* Update addon/services/router-scroll.js

Co-authored-by: Chantal Broeren <cbroeren@users.noreply.github.com>

* moar updates

* address moar feedback

Co-authored-by: Jan Buschtöns <jan@buschtoens.me>
Co-authored-by: John Leja <john.leja@dockyard.com>
Co-authored-by: Chantal Broeren <cbroeren@users.noreply.github.com>